//// Settings that belong to a deployment rather than to the build.
////
//// The bundle is compiled once and served as-is, so anything that should differ
//// per installation cannot live in it. The server renders the page and writes
//// these values into it as a JSON island in a `<script id="motto">`; they are
//// read back here while the app starts, before the first render.
////
//// When the frontend is served by `lustre/dev` on its own port, that page is
//// generated by the dev tools and carries no configuration, so
//// `default_motto` below is what shows. It is deliberately the same string the
//// server falls back to, so both agree on what an unconfigured shogging is.
////
//// Set `SHOGGING_MOTTO` on the server to change the motto.

import gleam/dynamic/decode.{type Decoder}
import gleam/json
import gleam/string
import plinth/browser/document
import plinth/browser/element.{text_content}

/// The id of the `<script>` the server writes the configuration into.
const config_id = "motto"

pub const default_motto = "Kaufe das Zeug!!!"

/// Read once, at startup. The answer cannot change without a page load.
pub fn motto() -> String {
  case document.get_element_by_id(config_id) {
    Error(_) -> default_motto
    Ok(element) -> decode_motto(text_content(element))
  }
}

fn decode_motto(payload: String) -> String {
  case json.parse(payload, motto_decoder()) {
    Ok(motto) -> or_default(motto)
    Error(_) -> default_motto
  }
}

fn motto_decoder() -> Decoder(String) {
  use motto <- decode.field("motto", decode.string)
  decode.success(motto)
}

/// A motto of nothing but whitespace would render as a blank line, which looks
/// like a bug rather than a setting.
fn or_default(motto: String) -> String {
  case string.trim(motto) {
    "" -> default_motto
    motto -> motto
  }
}
