
services:
  shogging:
    build: .
    container_name: shogging
    environment:
      CALDAV_HOST: ${CALDAV_HOST}
      CALDAV_USERNAME: ${CALDAV_USERNAME}
      CALDAV_PASSWORD: ${CALDAV_PASSWORD}
      CALDAV_CALENDAR: ${CALDAV_CALENDAR}
    restart: unless-stopped
    ports:
      - 1234:1234
