[tasks."server:dev"]
description = "Run dev server for shogging"
run = "gleam run"
depends = [ "server:tailwindcss" ]
dir = "server"

[tasks."server:tailwindcss"]
description = "Run tailwindcss on the server"
run = "mise exec npm:tailwindcss/cli -- tailwindcss -i ./src/css/app.css -o ./priv/tailwind.css"
dir = "server"

[tasks."shogg:test"]
description = "Run test for shogg"
run = "gleam test"
dir = "shogg"

[env]
CALDAV_HOST = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSBHdWU4WSt1S0FBQS9VNVVhbFYyNjZWWC9LN0VFYUxLYmorTEVRV3FjWHhvCkJXajVXQ2dJdEk3akdhaDZGZ0hLVFpQc3dRTVduWkI5WlFSY2VodU4rU3MKLT4gTEI1V2VQci1ncmVhc2UgRltxICYhSDMgegowcmNWaEVXMkdlay9xQTRIVEZsMENsQk9XaXY1RDR4NkdmZUtwK3AyZkZ2K3owWXdRdkY1eUsxSjlCNXlBb2dZClNDbnhZRGppQ3czQ3hKY2dsSEE0eFBEcm9oNHYrc2FMbUEKLS0tIHhJM0liNmhMRUFrcjY0UU5lR0FZNmtHMzgxd3pHTUxwblRnd0FDY2UzVVUKTHSmm8EnysxRk5YzIy3tlV5ze1bAVilDjqtrj1SWkspd8rvrh1g0VFWOqlBwGS8c" }
CALDAV_USERNAME = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSA0cFVNTjNnRHkxc2hUNHlnOVJ2RlpOOXpXNmsyemZlbHB0aWZURG9pZndnCko3UWVtcXV2VEhQT2V5bEZQSmZaMXVFU3F3MnRpTEJ4dSt4RURXZGVpUmsKLT4gfi1ncmVhc2UKbS9Nbms3QnNrVUJ2OVFJaG5OazlNTmh1aHlzaER4c0JHUlZvclo4WnlFZHI0NjhwTUJkZks1ZktzL0VFSC9vUAppTmcrNlFDWXFvdGdVakVICi0tLSBuOU5xbmlnamtLcXllQ1k0Z2ovQVJpSjlieE52SjNSclorZmhWcXdRQTNRCpjXQXOjaL9/UinVSQpEgft6IE2O79J4mJpEIftVqyuJJ0Sbb59yuO8" }
CALDAV_PASSWORD = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSBwWFkvZ3BIdkJ6RUhZRzVneWhVb3dVU3Zoc1FSMmRKa0FWcmwwM2VkQkdFCkRsN3F0bkhIdnZSUUpmUXFtQmhKWVJCQysyTURNdDd4OTc1c0VPdzM2d3cKLT4gNT4wY0hkLm4tZ3JlYXNlIFcgcig0azF+NyBtfXUgbQpKVjgzK1NoeEZPcU0vdnVkdVRQR0gwZkVMQmJOQXcrVDBMV2hyR2tkTURnTGF1SEdUZGU1QWM3akt6Wkt0dzV1Ckl0N0ZzZEcvZXlrakRPdWtQVmNjblpBejc1WFdtRGN1U1EKLS0tIGkxSk1kd1Z1YVk4dC9FdTI1TmE4VitPbzJncWNEMTFuaWxQZytweUtWYVUKYCh1XwdZilAa2AxKRjctKKXc8SWE+BXv8lX8wkZtpcyDLIuOVH5de67gp01fkAYJMEucSw+hNxQSEQF4Ag" }
CALDAV_CALENDAR = "Shogging Test"
CHECK_CHANGE_DELAY = "20"

[tools]
"npm:@tailwindcss/cli" = "latest"

# TODO: Add gleam, rebar, etc. here
