[tasks.watch]
description = "Watch for changes and rerun dev"
run = "watchexec --wrap-process=session --restart -iet 'clear && mise run dev'"

[tasks.dev]
description = "Run server for dev"
run = "gleam run"
dir = "server"


[env]
CALDAV_HOST = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSA3aGZqWnZJUWZod2tOcktzT2pQMWdJb2o5Vkl0bm15ME90ZHVkQ3JEcUFBCkttdmNKVWZRNFlBM0JvVXJtaFJ0bmV1MWd5ZmUzdW9kdFhTZS9JaDlrNmsKLT4gT3otZ3JlYXNlIGpvIDFCW3RQZmc6CmwzcWZDU1RGRGJ4MnRCbVpDM25FMFRnVG9WVWpQMCtXRlpJSjlaS2ZJQlFibm1CdEltNVlMNkdLSGIxTVY0QWYKQ3BzVDJBVzcwVnNJN3QzaGgxS3FWRlcrSU94ZndCRGh3cWwxNVBqTk5seW91eW1SeFZzZHBNRytNVlFkbGxvVgo0ZDgKLS0tIDBOZ1pWdTVTN0EvZDBWMnRDc3NiU1VoUHg5N0RPS1lJUEQ1Y1dpYmllazQK7coTsjW2QOuNTKRjEc2vM2wlvNP1ZqXp/H0AItYviH4BZztHRZ8ZtohpwgXSu5qKK1YFD7M" }
CALDAV_USERNAME = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSBjU3pFZnBzWXQ5QkVWc3k1dGlxc2JITkdSTXJaOWp3Rit6OU5RLzgycmc4CmpCbGI1ZzB6b2lubVVJK0ZlVXNKZDJsbGVDWFBLQ2Izek1rQkJZamZzcW8KLT4gcUwtZ3JlYXNlCnMwc1NyRnUvS2NUSzBLWGlJYUtsQ0JBCi0tLSBGeHJ0cTdFWVFZM2ZSVWRlM2FKeXQyTFVqYXdvZzhaTDRJT3ZEN1V5T2tNChkuzYighEOlQKYKi4Vl4w+PgaJfO3xgAlKe8vsEQlLKBrcWSSQ" }
CALDAV_PASSWORD = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHh3VnkzQSBxeHB2TnpjN0VRNk92cnBLMVZwZGxXVDFBUmNOei9ZaWpyQjNHYVVTempnCnE5NjNsRExZZ3J6dTBpbG4zemQvUkhObEpnOGxCaTFxVGQ5QkU3ckt0STgKLT4gQW5fcy1ncmVhc2UgSFY8PW8KMkNZSnk4c2VrdUlXSXZSQS9RZkN6ZVJUVXJkcUVyd0xDdWJpWWdMMThVc3ZhdUk4eFQyekQ5UzUrcWxFRU9jUApJcjFuWWdNLzViNVpRdThYdnNVNGxaUUZtNmk5R015bURVVGx2NWNPYU8rekZCSXN6MnRFVWVkVDJPRFMwMmN6CmlkawotLS0gRE5EajBEWk0vb3BWbWxJbm9OMGE1UUlmOUEwa1ZtWEhPYWVZQ2JLMlI3NAoKZ/yhck7G9E9xWdD88lMHp1tHnEH4CsK584Z9PINxs6lF9rZVmV2yAIR+2dYwSBFR/D45pb1WykzWpJyaHw8H9eqOqZHRczgwRbxIQ2OPY+M" }
CALDAV_CALENDAR = "Personal Calendar"
CHECK_CHANGE_DELAY = "20"

[tools]
watchexec = "latest"

# TODO: Add gleam, rebar, etc. here
